# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c700716df5ae428aa134a99cee66eab641227664fbf492d9c52634335b479184c86a8699b344b72858803c56f3ff1169a7032f967eebf9be285cc022c53f71d1

test:
  secret_key_base: 58f2024016ed3dd97b948e3aa787940d24bd9a962fdbce0b3a072211674531650aa3ab96e21ed170029ae82e8d9458a462b31dbef672afa40346a968e105050f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
